__attribute__((unused)) const int Nxx0 = params->Nxx0;  // grid::Nxx0
__attribute__((unused)) const int Nxx1 = params->Nxx1;  // grid::Nxx1
__attribute__((unused)) const int Nxx2 = params->Nxx2;  // grid::Nxx2
__attribute__((unused)) const int Nxx_plus_2NGHOSTS0 = params->Nxx_plus_2NGHOSTS0;  // grid::Nxx_plus_2NGHOSTS0
__attribute__((unused)) const int Nxx_plus_2NGHOSTS1 = params->Nxx_plus_2NGHOSTS1;  // grid::Nxx_plus_2NGHOSTS1
__attribute__((unused)) const int Nxx_plus_2NGHOSTS2 = params->Nxx_plus_2NGHOSTS2;  // grid::Nxx_plus_2NGHOSTS2
__attribute__((unused)) const REAL dxx0 = params->dxx0;  // grid::dxx0
__attribute__((unused)) const REAL dxx1 = params->dxx1;  // grid::dxx1
__attribute__((unused)) const REAL dxx2 = params->dxx2;  // grid::dxx2
__attribute__((unused)) const REAL xxmin0 = params->xxmin0;  // grid::xxmin0
__attribute__((unused)) const REAL xxmin1 = params->xxmin1;  // grid::xxmin1
__attribute__((unused)) const REAL xxmin2 = params->xxmin2;  // grid::xxmin2
__attribute__((unused)) const REAL xxmax0 = params->xxmax0;  // grid::xxmax0
__attribute__((unused)) const REAL xxmax1 = params->xxmax1;  // grid::xxmax1
__attribute__((unused)) const REAL xxmax2 = params->xxmax2;  // grid::xxmax2
__attribute__((unused)) const REAL invdx0 = params->invdx0;  // grid::invdx0
__attribute__((unused)) const REAL invdx1 = params->invdx1;  // grid::invdx1
__attribute__((unused)) const REAL invdx2 = params->invdx2;  // grid::invdx2
__attribute__((unused)) const REAL Cart_originx = params->Cart_originx;  // grid::Cart_originx
__attribute__((unused)) const REAL Cart_originy = params->Cart_originy;  // grid::Cart_originy
__attribute__((unused)) const REAL Cart_originz = params->Cart_originz;  // grid::Cart_originz
__attribute__((unused)) const REAL Cart_CoM_offsetx = params->Cart_CoM_offsetx;  // grid::Cart_CoM_offsetx
__attribute__((unused)) const REAL Cart_CoM_offsety = params->Cart_CoM_offsety;  // grid::Cart_CoM_offsety
__attribute__((unused)) const REAL Cart_CoM_offsetz = params->Cart_CoM_offsetz;  // grid::Cart_CoM_offsetz
__attribute__((unused)) const REAL bScale = params->bScale;  // reference_metric::bScale
__attribute__((unused)) const REAL SINHWAA = params->SINHWAA;  // reference_metric::SINHWAA
__attribute__((unused)) const REAL AMAX = params->AMAX;  // reference_metric::AMAX
__attribute__((unused)) const REAL eta_damping = params->eta_damping;  // NRPyElliptic.NRPyElliptic_RHSs::eta_damping
__attribute__((unused)) const REAL time = params->time;  // NRPyElliptic.NRPyElliptic_RHSs::time
__attribute__((unused)) const REAL puncture_0_bare_mass = params->puncture_0_bare_mass;
__attribute__((unused)) const REAL puncture_1_bare_mass = params->puncture_1_bare_mass;
__attribute__((unused)) const REAL puncture_0_x = params->puncture_0_x;
__attribute__((unused)) const REAL puncture_0_y = params->puncture_0_y;
__attribute__((unused)) const REAL puncture_0_z = params->puncture_0_z;
__attribute__((unused)) const REAL puncture_1_x = params->puncture_1_x;
__attribute__((unused)) const REAL puncture_1_y = params->puncture_1_y;
__attribute__((unused)) const REAL puncture_1_z = params->puncture_1_z;
__attribute__((unused)) const REAL puncture_0_P_x = params->puncture_0_P_x;
__attribute__((unused)) const REAL puncture_0_P_y = params->puncture_0_P_y;
__attribute__((unused)) const REAL puncture_0_P_z = params->puncture_0_P_z;
__attribute__((unused)) const REAL puncture_1_P_x = params->puncture_1_P_x;
__attribute__((unused)) const REAL puncture_1_P_y = params->puncture_1_P_y;
__attribute__((unused)) const REAL puncture_1_P_z = params->puncture_1_P_z;
__attribute__((unused)) const REAL puncture_0_S_x = params->puncture_0_S_x;
__attribute__((unused)) const REAL puncture_0_S_y = params->puncture_0_S_y;
__attribute__((unused)) const REAL puncture_0_S_z = params->puncture_0_S_z;
__attribute__((unused)) const REAL puncture_1_S_x = params->puncture_1_S_x;
__attribute__((unused)) const REAL puncture_1_S_y = params->puncture_1_S_y;
__attribute__((unused)) const REAL puncture_1_S_z = params->puncture_1_S_z;
__attribute__((unused)) const char * initial_lapse = params->initial_lapse;
__attribute__((unused)) const REAL lapse_exponent = params->lapse_exponent;
__attribute__((unused)) const int has_outer_boundary = params->has_outer_boundary;  // CurviBoundaryConditions.CurviBoundaryConditions_new_way::has_outer_boundary
