# Define dictionary of parameters
params_dict = {}
# Physical Parameters
b = 6.0
#params_dict["wavespeed"]           = ("REAL", 1.0)
params_dict["eta_damping"]         = ("REAL", 12.5)
params_dict["bare_mass_0"]         = ("REAL", 0.5)
params_dict["bare_mass_1"]         = ("REAL", 0.5)
params_dict["puncture_0_x"]        = ("REAL", 0.0)
params_dict["puncture_0_y"]        = ("REAL", 0.0)
params_dict["puncture_0_z"]        = ("REAL", b)
params_dict["puncture_1_x"]        = ("REAL", 0.0)
params_dict["puncture_1_y"]        = ("REAL", 0.0)
params_dict["puncture_1_z"]        = ("REAL", -b)
params_dict["P0_x"]                = ("REAL", 0.0)
params_dict["P0_y"]                = ("REAL", 0.0)
params_dict["P0_z"]                = ("REAL", 0.0)
params_dict["P1_x"]                = ("REAL", 0.0)
params_dict["P1_y"]                = ("REAL", 0.0)
params_dict["P1_z"]                = ("REAL", 0.0)
params_dict["S0_x"]                = ("REAL", 0.0)
params_dict["S0_y"]                = ("REAL", 0.0)
params_dict["S0_z"]                = ("REAL", 0.4)
params_dict["S1_x"]                = ("REAL", 0.0)
params_dict["S1_y"]                = ("REAL", 0.0)
params_dict["S1_z"]                = ("REAL", -0.4)
# NRPy+/grid parameters
params_dict["CoordSystem"]         = ("str", "SinhSymTP")
params_dict["BoundaryCondition"]   = ("str", "Sommerfeld")
params_dict["domain_size"]         = ("REAL", 1.0e6)
params_dict["sinh_width"]          = ("REAL", 0.07)
params_dict["sinhv2_const_dr"]     = ("REAL", 0.01)
params_dict["SymTP_bScale"]        = ("REAL", b)
params_dict["RK_method"]           = ("str", "RK4")
params_dict["FD_order"]            = ("int", 10)
params_dict["FD_order_Sommerfeld"] = ("int", 6)
params_dict["CFL_FACTOR"]          = ("REAL", 0.7)
params_dict["N0"]                  = ("int", 128)
params_dict["N1"]                  = ("int", 128)
params_dict["N2"]                  = ("int", 6)
# NRpyElliptic parameters
params_dict["number_of_LCT"]       = ("REAL", 3.5e-6)
params_dict["target_log_residual"] = ("REAL", -12.0)
params_dict["excision_radius"]     = ("REAL", 0.0)
# TwoPunctures parameters
params_dict["npoints_A"]     = ("int", 64)
params_dict["npoints_B"]     = ("int", 64)
params_dict["npoints_phi"]   = ("int", 4)
params_dict["Newton_tol"]    = ("REAL", 1.0e-14)
params_dict["Newton_maxit"]  = ("int", 5)
params_dict["give_bare_mass"] = ("bool", 1)
params_dict["read_u_punc_from_checkpoint"] = ("bool", 0)
params_dict["u_punc_checkpoint_file_path"] = ("str", "NULL")
# Execution parameters
params_dict["give_cores"] = ("bool", 0)
params_dict["cores_list"] = ("list", [])