CCTK_ATTRIBUTE_UNUSED const double NOSIMDf0_of_xx0 = rfmstruct->f0_of_xx0[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f0_of_xx0 = ConstSIMD(NOSIMDf0_of_xx0);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf0_of_xx0__D0 = rfmstruct->f0_of_xx0__D0[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f0_of_xx0__D0 = ConstSIMD(NOSIMDf0_of_xx0__D0);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf0_of_xx0__DD00 = rfmstruct->f0_of_xx0__DD00[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f0_of_xx0__DD00 = ConstSIMD(NOSIMDf0_of_xx0__DD00);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf0_of_xx0__DDD000 = rfmstruct->f0_of_xx0__DDD000[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f0_of_xx0__DDD000 = ConstSIMD(NOSIMDf0_of_xx0__DDD000);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf2_of_xx0_xx1 = rfmstruct->f2_of_xx0_xx1[i0 + Nxx_plus_2NGHOSTS0*i1]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f2_of_xx0_xx1 = ConstSIMD(NOSIMDf2_of_xx0_xx1);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf2_of_xx0_xx1__D0 = rfmstruct->f2_of_xx0_xx1__D0[i0 + Nxx_plus_2NGHOSTS0*i1]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f2_of_xx0_xx1__D0 = ConstSIMD(NOSIMDf2_of_xx0_xx1__D0);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf2_of_xx0_xx1__D1 = rfmstruct->f2_of_xx0_xx1__D1[i0 + Nxx_plus_2NGHOSTS0*i1]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f2_of_xx0_xx1__D1 = ConstSIMD(NOSIMDf2_of_xx0_xx1__D1);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf2_of_xx0_xx1__DD00 = rfmstruct->f2_of_xx0_xx1__DD00[i0 + Nxx_plus_2NGHOSTS0*i1]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f2_of_xx0_xx1__DD00 = ConstSIMD(NOSIMDf2_of_xx0_xx1__DD00);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf2_of_xx0_xx1__DD11 = rfmstruct->f2_of_xx0_xx1__DD11[i0 + Nxx_plus_2NGHOSTS0*i1]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f2_of_xx0_xx1__DD11 = ConstSIMD(NOSIMDf2_of_xx0_xx1__DD11);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf3_of_xx0 = rfmstruct->f3_of_xx0[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f3_of_xx0 = ConstSIMD(NOSIMDf3_of_xx0);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf3_of_xx0__D0 = rfmstruct->f3_of_xx0__D0[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f3_of_xx0__D0 = ConstSIMD(NOSIMDf3_of_xx0__D0);
CCTK_ATTRIBUTE_UNUSED const double NOSIMDf3_of_xx0__DD00 = rfmstruct->f3_of_xx0__DD00[i0]; CCTK_ATTRIBUTE_UNUSED const REAL_SIMD_ARRAY f3_of_xx0__DD00 = ConstSIMD(NOSIMDf3_of_xx0__DD00);
